### ISSUE TITLE
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0

### ISSUE THREAD

**Issue by forgottenbutnotgone** [stefansundin/truecrypt.deb#3]
libwxgtk3.0-dev was changed to libwxgtk3.0-gtk3-dev in Ubuntu 20.04.

Fails to compile using gcc (Ubuntu 11.2.0-19ubuntu1) in Ubuntu 22.04.

**Comment by stefansundin** [comment]
Sorry but I missed this when you originally filed it. My apologies.

I don't think this is relevant anymore since it appears that Ubuntu 24.04 changed it back with `libwxgtk3.2-dev`.

Please reopen if there's more to this. Thanks!
